ReadQuest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('leaderboard.urls')),
    path('', include('Inventory.urls')),
    path('', include('make_journey_jurnal.urls')),
    path('forum/', include('round_table.urls')),
    path('', include('quest.urls')),
]

books/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Your existing URL patterns
    path('search/', views.search_books, name='search_books'),
    path('add-books/', views.add_books, name='add_books'),
    path('remove-book/', views.remove_book, name='remove_book'),
    path('', views.display_all_books, name='display_all_books'),
    path('books-dataset/', views.books_dataset, name='books_dataset'),
    path('book-detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('add-book-to-inventory/<int:book_id>/', views.add_book_to_inventory, name='add_book_to_inventory'),
    path('book-act/<int:pk>/', views.book_act, name='book_act'),
    path('json-all/', views.view_json, name='json_all'),
    path('json-book/<int:pk>/', views.book_detail_json, name='book_detail_json'),
    path('add-book-to-inventory-flutter/<int:book_id>/', views.add_book_to_inventory_flutter, name='add_book_to_inventory_flutter'),
    path('json-book/<int:id>', views.view_json_book_id, name='json_book_id'),
]

round_table/urls.py
from django.urls import path
from .views import *

app_name = 'round_table'

urlpatterns = [
    # Your existing URL patterns
    path('', show_all_forum, name='show_all_forum'),
    path('add-forum/', add_forum, name='add_forum'),
    path('add-forum/<int:book_id>', add_forum, name='add_forum'),
    path('add-reply/<int:id>/', add_reply, name='add_reply'),
    path('<int:id>/', forum_detail, name='forum_detail'),
    path('delete-forum/<int:id>/', delete_forum, name='delete_forum'),
    path('delete-reply/<int:id>/', delete_reply, name='delete_reply'),
    path('search/', search_forums, name='search_forums'),
    path('get-forum/', get_forums_json, name='get_forums_json'),
    path('delete-forum-ajax/<int:id>/', delete_forum_ajax, name='delete_forum_ajax'),
    path('<int:forum_id>/get-replies/', get_replies_json, name='get_replies_json'),
    path('<int:forum_id>/delete-reply-ajax/<int:reply_id>/', delete_reply_ajax, name='delete_reply_ajax'),
    path('create-forum/', create_forum_flutter, name='create_forum_flutter'),
    path('create-replies/', create_replies_flutter, name='create_replies_flutter'),
    path('delete-forum-flutter/<int:id>/', delete_forum_flutter, name='delete_forum_flutter'),
]

round_table/models.py
from django.db import models
from users.models import User
from books.models import Book

class Forum(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)

class Replies(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    parent_forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    content = models.TextField(max_length=5000) 
    created_at = models.DateTimeField(auto_now_add=True)

round_table/forms.py
from django.forms import ModelForm, ModelChoiceField
from round_table.models import Forum, Replies
from books.models import Book
 
class CreateForum(ModelForm):
    def __init__(self, *args, **kwargs):
        book_id = kwargs.pop("book_id", None)
        super(CreateForum, self).__init__(*args, **kwargs)
        if book_id is not None:
            self.fields["book"].initial = book_id

    book = ModelChoiceField(
        queryset=Book.objects.all(),
        empty_label="Select a book",
    )
    class Meta:
        model = Forum
        fields = ["book", "title", "content"]
 
class CreateReplies(ModelForm):
    class Meta:
        model = Replies
        fields = ["content"]

round_table/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from books.models import Book
from round_table.models import Forum, Replies
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from .forms import CreateForum, CreateReplies
from django.db.models import Q

def roler(user):
    if user.is_anonymous:
        role = 'none'
    elif user.role == "PENGGUNA":
        role = 'pengguna'
    elif user.role == "ADMIN":
        role = 'admin'
    return role

def show_all_forum(request):
    forums = Forum.objects.all()
    return render(request, 'forum.html', {'forums':forums,'role':roler(request.user)})

def forum_detail(request, id):
    forum = get_object_or_404(Forum, id=id)
    replies = Replies.objects.filter(parent_forum=forum)
    book = forum.book
    return render(request, 'forum_detail.html', {'forum':forum,'replies':replies,'role':roler(request.user), 'book':book})

@csrf_exempt
def add_forum(request, book_id=None):
    form = CreateForum(book_id=book_id)

    if request.user.is_anonymous:
        return redirect('user:login')
    elif request.method == 'POST':
        form = CreateForum(request.POST, book_id=book_id)
        if form.is_valid():
    
            forum = form.save(commit=False)
            forum.author = request.user
            forum.save()
            return redirect('round_table:show_all_forum')

    return render(request, 'add_forum.html', {'form':form,'role':roler(request.user)})

@csrf_exempt
def add_reply(request, id):
    forum = get_object_or_404(Forum, id=id)
    form = CreateReplies(request.POST or None)
    
    if request.user.is_anonymous:
        return redirect('user:login')
    elif form.is_valid() and request.method == 'POST':
        reply = form.save(commit=False)
        reply.parent_forum = forum
        reply.author = request.user
        reply.save()
        return redirect('round_table:forum_detail', id=id)

    return render(request, 'add_reply.html', {'forum':forum,'form':form,'role':roler(request.user)})

def delete_forum(request, id):
    forum = get_object_or_404(Forum, id=id)
    
    if request.user == forum.author:
        forum.delete()
        return redirect('round_table:show_all_forum')
    
    return redirect('round_table:forum_detail', id=id)
  
def delete_reply(request, id):
    reply = get_object_or_404(Replies, id=id)
    
    if request.user == reply.author:
        reply.delete()
        return redirect('round_table:forum_detail', id=id)
    
    return redirect('round_table:forum_detail', id=id)

def search_forums(request):
    if 'q' in request.GET:
        query = request.GET['q']
        title_results = Forum.objects.filter(title__icontains=query)
        content_results = Forum.objects.filter(content__icontains=query)
        book_results = Forum.objects.filter(
            Q(book__title__icontains=query) | Q(book__author__icontains=query)
        )
        results = title_results.union(content_results)
        results = results.union(book_results)
    else:
        results = None
    return render(request, 'search_forums.html', {'results': results,'q':query,'username':request.user.username,'role':roler(request.user)})

def get_forums_json(request):
    forums = Forum.objects.all()
    forum_data = []

    for forum in forums:
        data = {
            "id": forum.id,
            "book_title": forum.book.title,
            "book_author": forum.book.author,
            "book_thumbnail": forum.book.image_url,
            "title": forum.title,
            "content": forum.content,
            "author": forum.author.username,
            "created_at": forum.created_at,
            "is_owner": request.user == forum.author,
        }
        forum_data.append(data)

    return JsonResponse(forum_data, safe=False)

@csrf_exempt
def delete_forum_ajax(request, id):
    if request.method == 'DELETE':
        item = get_object_or_404(Forum, id=id)
        item.delete()
        return HttpResponse(b"DELETED", status=200)
    
    return HttpResponseNotFound()

def get_replies_json(request, forum_id):
    forum = get_object_or_404(Forum, id=forum_id)
    replies = Replies.objects.filter(parent_forum=forum)
    forum_data = []

    for reply in replies:
        data = {
            "id": reply.id,
            "ForumId": forum_id,
            "content": reply.content,
            "author": reply.author.username,
            "created_at": reply.created_at,
            "is_owner": request.user == reply.author,
        }
        forum_data.append(data)

    return JsonResponse(forum_data, safe=False)

@csrf_exempt
def delete_reply_ajax(request, forum_id, reply_id):
    if request.method == 'DELETE':
        item = get_object_or_404(Replies, id=reply_id)
        item.delete()
        return HttpResponse(b"DELETED", status=200)
    
    return HttpResponseNotFound()

@csrf_exempt
def create_forum_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        book_from_id = get_object_or_404(Book, pk=int(data['book']))

        new_forum = Forum.objects.create(
            author = request.user,
            book = book_from_id,
            title = data["title"],
            content = data["content"],
        )
        new_forum.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def create_replies_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)
        parent_forum_from_id = get_object_or_404(Forum, pk=int(data['parent_forum']))

        new_replies = Replies.objects.create(
            author = request.user,
            parent_forum = parent_forum_from_id,
            content = data["content"],
        )

        new_replies.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def delete_forum_flutter(request, id):
    if request.method == 'DELETE':
        forum = get_object_or_404(Forum, pk=id)
        forum.delete()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

round_table/templates/add_forum.html
{% extends 'base.html' %} 

{% block content %}
{% load static %}
<head>
    <title>Add Forum</title>
    <link rel="stylesheet" href="/static/round_table/styles/add_forum.css">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-16">
                <div class="card">
                    <div class="header">
                        <div class="row justify-content-center">
                            <h1 class="card-title justify-content-center">Add New Forum</h1>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                                <div>
                                    <label for="id_book" class="col-form-label">Book:</label>
                                    <div>
                                        {{ form.book }}
                                    </div>
                                    <label for="id_title" class="col-form-label">Title:</label>
                                    <input name="title" type="text" class="form-control mb-3" class="form-control mb-3" cols="160" maxlength="100" required="" id="id_title" placeholder="Your text here..."></input>
                                    <label for="id_content" class="col-form-label">Description:</label>
                                    <textarea name="content" class="form-control mb-3" cols="160" rows="10" maxlength="5000" required="" id="id_content" style="height: 129px;" placeholder="Your text here..."></textarea>
                                </div>
                            <a href="{% url 'round_table:show_all_forum' %}" class="btn btn-secondary">Back to Forums</a>
                            <button type="submit" class="btn btn-submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

round_table/templates/add_reply.html
{% extends 'base.html' %} 

{% block content %}
{% load static %}
<head>
    <title>Add Forum</title>
    <link rel="stylesheet" href="/static/round_table/styles/add_reply.css   ">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-16">
                <div class="card">
                    <div class="header">
                        <h1 class="card-title">Add New Reply</h1>
                        <p class="card-text">Replying: {{ forum.title }}</p>
                        <p class="card-text">{{ forum.content }}</p>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for elem in form%}
                            <div>
                                <textarea name="content" class="form-control mb-3" cols="160" rows="10" maxlength="5000" required="" id="id_content" style="height: 129px;" placeholder="Your text here..."></textarea>
                            </div>
                            {% endfor %}
                            <a href="{% url 'round_table:forum_detail' forum.id %}" class="btn btn-secondary">Back</a>
                            <button type="submit" class="btn btn-add-reply">Add Reply</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

round_table/templates/forum.html
{% extends 'base.html' %} 

{% block content %}
{% load static %}
<head>
  <title>Forum</title>
  <link rel="stylesheet" href="/static/round_table/styles/forum.css">
</head>

<div class="centered">
  <div class="round_table_title">
    <div class="cloud"></div>
    <div class="cloud"></div>
    <div class="cloud"></div>
    <div class="cloud"></div>
    <div class="cloud"></div>
    <h1 class="poppins">Round Table</h1>
    {% if user.is_authenticated %}
      <a href="{% url 'round_table:add_forum' %}"><button class="add-forum-btn">Add Forum</button></a>
    {% endif %}
  </div>
</div>

<div class="row w-100" id="forums"></div>

<script>
  async function getForums() {
      return fetch("{% url 'round_table:get_forums_json' %}").then((res) => res.json())
  }

  async function refreshForums() {
      document.getElementById("forums").innerHTML = ""
      const forums = await getForums()
      let htmlString = ``
      forums.forEach((forum) => {
          htmlString += `<div class="card w-100 ml-5 mr-4 mt-3">
            <a href="${forum.id}" style="color:inherit;text-decoration:none;">
              <div class="card-header">
                <div class="cloud-header"></div>
                <div class="cloud-header"></div>
                <div class="cloud-header"></div>
                <div class="cloud-header"></div>
                <div style="display: flex; justify-content: space-between;">
                  <h5 class="card-title">${forum.title}</h5>
                  </a>
                  ${forum.is_owner ? `<button class="btn btn-danger btn-delete" onclick="deleteForum(${forum.id})"><img src="/static/round_table/icon/delete_icon.png"></button>` : ""}
                </div>
            <a href="${forum.id}" style="color:inherit;text-decoration:none;">
              <p class="card-text" style="margin-bottom:0px">Discussing ${forum.book_title} by ${forum.book_author}</p>
              <p class="card-text" style="margin-top:0px">${forum.author} - Posted on ${formatDate(forum.created_at)}</p>
              </div>
              <a href="${forum.id}" style="color:inherit;text-decoration:none;">
              <div class="card-body">
                <p class="card-text">${truncateText(forum.content, 200)}</p>
              </div>
              </a>
            </a>
          </div>`; 
      })
      
      document.getElementById("forums").innerHTML = htmlString
  }

  refreshForums()

  function deleteForum(id) {
    const isConfirmed = confirm("Are you sure you want to delete this forum? all of the replies will be deleted too");

    if (isConfirmed) {
      fetch(`delete-forum-ajax/${id}/`, {
        method: "DELETE",
      }).then(refreshForums);
    }

    return false;
  }

  function truncateText(text, maxLength) {
    if (text && text.length > maxLength) {
        return text.slice(0, maxLength) + '...';
    }
    return text;
  }

  function formatDate(dateString) {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(dateString);
    return date.toLocaleDateString('en-GB', options);
  }
</script>
{% endblock %}

round_table/templates/forum_detail.html
{% extends 'base.html' %} 

{% block content %}
{% load static %}
<head>
  <title>{{ forum.title }}</title>
  <link rel="stylesheet" href="/static/round_table/styles/forum_detail.css">
</head>
<div class="row w-100">
  <div class="card w-100 ml-5 mr-4 mt-3">
    <div class="header">
      <div style="display: flex; justify-content: space-between;">
        <h5 class="card-title">{{ forum.title }}</h5>
        {% if user.is_authenticated and user == forum.author %}
          <a href="{% url 'round_table:delete_forum' forum.id %}"><button class="btn-delete"><img src="/static/round_table/icon/delete_icon.png"></button></a>
        {% endif %}
      </div>
      <p class="card-text" style="margin-bottom:0px">Discussing {{forum.book.title}} by {{forum.book.author}}</p>
      <p class="card-text">{{ forum.author.username }} - Posted on {{ forum.created_at|date:"d F Y" }}</p>
    </div>
    <div class="card-body">
      <div class="centered">
        <img class="img-thumbnail" src="{{ forum.book.image_url }}" alt="{{ forum.book.title }}">
      </div>
        <p class="card-text">{{ forum.content|linebreaks }}</p>
        <a href="{% url 'round_table:show_all_forum' %}"><button class="btn-secondary">Back to Forums</button></a>
        {% if user.is_authenticated %}
          <a href="{% url 'round_table:add_reply' forum.id %}"><button class="btn-add-reply">Add Reply</button></a>
        {% endif %}
    </div>
  </div>
</div>
<div class="centered">
  <div class="replies-text">
    <h2 class="centered">Replies</h2>
  </div>
</div>
<div class="row w-100" id="replies"></div>

<script>
  async function getReplies(forumId) {
    return fetch(`/forum/${forumId}/get-replies/`).then((res) => res.json())
  }

  async function refreshReplies(forumId) {
    document.getElementById("replies").innerHTML = ""
    const replies = await getReplies(forumId)
    let htmlString = ``
    replies.forEach((reply) => {
        htmlString += `<div class="card w-100 ml-5 mr-4 mt-2">
            <div class="header">
              <div style="display: flex; justify-content: space-between;">
                <p class="card-text">${reply.author} - Replied on ${formatDate(reply.created_at)}</p>
                ${reply.is_owner ? `<button class="btn-delete" onclick="deleteReply(${reply.id})"><img src="/static/round_table/icon/delete_icon.png"></button>` : ""}
              </div>
            </div>
            <div class="card-body">
              <p class="card-text">${reply.content}</p>
            </div>
        </div>`; 
    })
    
    document.getElementById("replies").innerHTML = htmlString
  }

  const url = window.location.href.split("/");
  let forumId;
  if (url[url.length - 1] === "") {
    forumId = url[url.length - 2];
  } else {
    forumId = url[url.length - 1];
  }
  
  refreshReplies(forumId)

  function deleteReply(id) {
    const isConfirmed = confirm("Are you sure you want to delete this reply?");

    if (isConfirmed) {
      fetch(`delete-reply-ajax/${id}`, {
          method: "DELETE",
      }).then(refreshReplies)
    }
    
    return false
  }

  function formatDate(dateString) {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(dateString);
    return date.toLocaleDateString('en-GB', options);
  }
</script>
{% endblock %}

round_table/templates/search_forums.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
    <title>Search Forum</title>
    <link rel="stylesheet" href="/static/round_table/styles/forum.css">
</head>
{% if results %}
    <ul>
        <h1 class="mt-5">Search Results</h1>
            {% for forum in results %}
                <div class="row w-100">
                    <div class="card w-100 ml-3 mr-3 mt-3">
                        <div class="header">
                            <div style="display: flex; justify-content: space-between;">
                              <h5 class="card-title">{{ forum.title }}</h5>
                              {% if user.is_authenticated and user == forum.author %}
                                <a href="{% url 'round_table:delete_forum' forum.id %}"><button class="btn-delete"><img src="/static/round_table/icon/delete_icon.png"></button></a>
                              {% endif %}
                            </div>
                            <p class="card-text" style="margin-bottom:0px">Discussing {{forum.book.title}} by {{forum.book.author}}</p>
                            <p class="card-text">{{ forum.author.username }} - Posted on {{ forum.created_at|date:"d F Y" }}</p>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ forum.content|truncatewords:50|linebreaks }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </ul>
{% else %}
    <p>No results found.</p>
{% endif %}
{% endblock content %}