ReadQuest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('leaderboard.urls')),
    path('', include('Inventory.urls')),
    path('', include('make_journey_jurnal.urls')),
    path('forum/', include('round_table.urls')),
    path('', include('quest.urls')),
]

books/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Your existing URL patterns
    path('search/', views.search_books, name='search_books'),
    path('add-books/', views.add_books, name='add_books'),
    path('remove-book/', views.remove_book, name='remove_book'),
    path('', views.display_all_books, name='display_all_books'),
    path('books-dataset/', views.books_dataset, name='books_dataset'),
    path('book-detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('add-book-to-inventory/<int:book_id>/', views.add_book_to_inventory, name='add_book_to_inventory'),
    path('book-act/<int:pk>/', views.book_act, name='book_act'),
    path('json-all/', views.view_json, name='json_all'),
    path('json-book/<int:pk>/', views.book_detail_json, name='book_detail_json'),
    path('add-book-to-inventory-flutter/<int:book_id>/', views.add_book_to_inventory_flutter, name='add_book_to_inventory_flutter'),
    path('json-book/<int:id>', views.view_json_book_id, name='json_book_id'),
]

round_table/urls.py
from django.urls import path
from .views import *

app_name = 'round_table'

urlpatterns = [
    # Your existing URL patterns
    path('', show_all_forum, name='show_all_forum'),
    path('add-forum/', add_forum, name='add_forum'),
    path('add-forum/<int:book_id>', add_forum, name='add_forum'),
    path('add-reply/<int:id>/', add_reply, name='add_reply'),
    path('<int:id>/', forum_detail, name='forum_detail'),
    path('delete-forum/<int:id>/', delete_forum, name='delete_forum'),
    path('delete-reply/<int:id>/', delete_reply, name='delete_reply'),
    path('search/', search_forums, name='search_forums'),
    path('get-forum/', get_forums_json, name='get_forums_json'),
    path('delete-forum-ajax/<int:id>/', delete_forum_ajax, name='delete_forum_ajax'),
    path('<int:forum_id>/get-replies/', get_replies_json, name='get_replies_json'),
    path('<int:forum_id>/delete-reply-ajax/<int:reply_id>/', delete_reply_ajax, name='delete_reply_ajax'),
    path('create-forum/', create_forum_flutter, name='create_forum_flutter'),
    path('create-replies/', create_replies_flutter, name='create_replies_flutter'),
    path('delete-forum-flutter/<int:id>/', delete_forum_flutter, name='delete_forum_flutter'),
]

books/models.py
from django.db import models
from users.models import User

class Book(models.Model):
    isbn = models.CharField(max_length=100)
    def __str__(self):
        return self.title
    
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    published_date = models.TextField()
    thumbnail = models.URLField()
    readed = models.IntegerField(default=0)
    publisher = models.CharField(max_length=255)
    publication_date = models.CharField(max_length=100)
    page_count = models.IntegerField()
    category = models.CharField(max_length=255)
    image_url = models.URLField()
    lang = models.CharField(max_length=100)
    readed = models.IntegerField(default=0)
    buys = models.IntegerField(default=0)
    quest_amount = models.IntegerField(default=0)

class BookRead(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_read = models.DateTimeField(auto_now=True)

class BookBought(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_bought = models.DateTimeField(auto_now=True)

class BookReviewed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_reviewed = models.DateTimeField(auto_now=True)

books/views.py
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
import requests
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from Inventory.models import Inventory, InventoryBook
from users.views import custom_login
from quest.views import roler
from django.db import models
from quest.views import quest_point
from django.core import serializers


# Create your views here.

api = 'AIzaSyDXkWtSpUh78YnFk1AFNBvszdmxffY2nEI'

def add_books_from_google_books_api(query, api_key):
    url = f'https://www.googleapis.com/books/v1/volumes?q={query}&key={api_key}'
    response = requests.get(url)
    data = response.json()

    if 'items' in data:
        
        for item in data['items']:
            if len(Book.objects.all()) >= 100 :
                return
            book_info = item.get('volumeInfo', {})
            title = book_info.get('title', '')
            author = ', '.join(book_info.get('authors', []))
            description = book_info.get('description', '')
            published_date = book_info.get('publishedDate', '')
            thumbnail = book_info['imageLinks']['thumbnail'] if 'imageLinks' in book_info else ''

            # Save the book to the database
            Book.objects.create(
                title=title,
                author=author,
                description=description,
                published_date=published_date,
                thumbnail=thumbnail,
                publisher=book_info.get('publisher', ''),  # Sesuaikan dengan data yang ada di API
                publication_date=book_info.get('publishedDate', ''),  # Sesuaikan dengan data yang ada di API
                page_count=book_info.get('pageCount', 0),  # Sesuaikan dengan data yang ada di API
                category=book_info.get('categories', ''),  # Sesuaikan dengan data yang ada di API
                image_url=book_info.get('imageLinks', {}).get('thumbnail', ''),  # Sesuaikan dengan data yang ada di API
                lang=book_info.get('language', ''),  # Sesuaikan dengan data yang ada di API
            )

def add_books(request):
    user = request.user
    if user.is_anonymous or user.role == "PENGGUNA":
        return render(request, '404.html', {'role':roler(request)})
    if request.method == 'POST':
        query = request.POST.get('query', '')  # Retrieve the query from the form
        api_key = 'AIzaSyDXkWtSpUh78YnFk1AFNBvszdmxffY2nEI'

        # Add books based on the query using add_books_from_google_books_api function
        add_books_from_google_books_api(query, api_key)
    return render(request, 'add_books.html', {'username':user.username, 'role':roler(request)})


def display_all_books(request):
    books = Book.objects.all()
    user = request.user
    if not user.is_anonymous:
        quest_point(request)
    if user.is_anonymous:
        user = "none"
        return render(request, 'book.html', {'books': books, 'user':user, 'role':'not login'})
    elif user.role == "PENGGUNA":
        username = user.username
        point = user.point
        return render(request, 'book.html', {'books': books, 'username':username, 'point':point, 'role':'pengguna'})
    elif user.role == "ADMIN" :
        username = user.username
        return render(request, 'book.html', {'books': books, 'username':username, 'role':'admin'})
    return render(request, 'book.html', {'books': books, 'username' : user.username, 'role':'none'})

def books_dataset(request):
    books = Book.objects.all()
    return render(request, 'books.html', {'books': books})


from django.shortcuts import render, get_object_or_404
from .models import Book
from users.models import User
from .models import BookRead, BookBought, BookReviewed
from django.views.decorators.csrf import csrf_exempt

def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    user = request.user
    finish = []
    user_inventories = None
    
    if user.is_authenticated:
        quest_point(request)
        if BookRead.objects.filter(user=user, book=book).exists():
            finish.append("readed")
        if BookBought.objects.filter(user=user, book=book).exists():
            finish.append("buyed")
        if BookReviewed.objects.filter(user=user, book=book).exists():
            finish.append("reviewed")
        user_inventories = Inventory.objects.filter(user=user)

    return render(request, 'book_detail.html', {'book': book, 'user_inventories': user_inventories, 'role':roler(request), 'finish': finish})

@csrf_exempt
def book_act(request, pk):
    user = request.user
    if request.method == 'POST':
        act = request.POST.get("status")
        book = Book.objects.get(pk=pk)

        if act == "readed":
            # Check if the user has already read the book
            if not BookRead.objects.filter(user=user, book=book).exists():
                # Increment the user's count of read books
                # user.readed += 1
                User.objects.filter(pk=user.pk).update(readed=models.F('readed') + 1)
                # user.save()
                BookRead.objects.create(user=user, book=book)

        elif act == "bought":
            # Check if the user has already bought the book
            if not BookBought.objects.filter(user=user, book=book).exists():
                # Increment the user's count of bought books
                # user.buyed += 1
                # user.save()
                User.objects.filter(pk=user.pk).update(buyed=models.F('buyed') + 1)
                BookBought.objects.create(user=user, book=book)

        elif act == "reviewed":
            # Check if the user has already reviewed the book
            if not BookReviewed.objects.filter(user=user, book=book).exists():
                # Increment the user's count of reviewed books
                # user.reviewed += 1
                # user.save()
                User.objects.filter(pk=user.pk).update(reviewed=models.F('reviewed') + 1)
                BookReviewed.objects.create(user=user, book=book)
    return redirect('books:book_detail', pk=pk)

@csrf_exempt
def remove_book(request):
    user = request.user
    if user.is_anonymous or user.role == "PENGGUNA":
        return render(request, '404.html', {'role':roler(request)})
    if request.method == 'POST':
        pk = request.POST.get('pk', None)
        if pk is not None:
            book = get_object_or_404(Book, pk=pk)
            book.delete()
    return render(request, 'remove_book.html', {'username':user.username, 'role':roler(request)})

def search_books(request):
    user = request.user
    if 'q' in request.GET:
        query = request.GET['q']
        results = Book.objects.filter(title__icontains=query)
    else:
        results = None
    role = 'none'
    if user.is_anonymous:
        return render(request, 'search_result.html', {'results': results, 'q':query, 'username':user.username, 'role':role})
    if user.role == "PENGGUNA":
        role = 'pengguna'
    elif user.role == "ADMIN":
        role = 'admin'
    return render(request, 'search_result.html', {'results': results, 'q':query, 'username':user.username, 'role':role})

def add_book_to_inventory(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    user = request.user
    if request.method == 'POST':
        folder_id = request.POST.get('folder')

        folder = get_object_or_404(Inventory, pk=folder_id)

        if folder.user == user:
            if not InventoryBook.objects.filter(inventory=folder, book=book).exists():
                inventory_book = InventoryBook.objects.create(inventory=folder, book=book)
                return redirect('books:book_detail', pk=book_id)
    return redirect('books:book_detail', pk=book_id)

def view_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def book_detail_json(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = serializers.serialize("json", [book])

    return HttpResponse(data, content_type="application/json")

@csrf_exempt
def add_book_to_inventory_flutter(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST':
        data = json.loads(request.body)
        inventory_data_str = json.dumps(data.get('Inventory.inventorybook', []))
        if inventory_data_str:
            inventory_data = json.loads(inventory_data_str)
            if inventory_data:
                inventory_entry = inventory_data[0]
                this_inventory = inventory_entry.get("fields")
                inventory_id = this_inventory.get('inventory')
                inventory = get_object_or_404(Inventory, pk=inventory_id)
                if not InventoryBook.objects.filter(inventory = inventory, book = book).exists():
                    add_book = InventoryBook.objects.create(
                        inventory =  inventory,
                        book = book,
                    )

                    add_book.save()

                    return JsonResponse({"status": "success"}, status=200)
                else:
                    return JsonResponse({"status": "exist"}, status=200)

    else:
        return JsonResponse({"status": "error"}, status=401)

def view_json_book_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

books/templates/add_books.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>Add Books from Google Books API</title>
</head>
<body>
    <h1>Add Books from Google Books API</h1>
    
    <form method="post" action="{% url 'books:add_books' %}">
        {% csrf_token %}
        <label for="query">Enter a search query (e.g., title, author, keyword):</label>
        <input type="text" id="query" name="query" required>
        <button type="submit">Search and Add Books</button>
    </form>
    
    <a href="{% url 'books:display_all_books' %}">Back to Home</a>
</body>
{% endblock content %}

books/templates/book.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<html>
<head>
    <title>Books List</title>
    <link rel="stylesheet" href="{% static 'book/styles/book.css' %}"/>
    <style>
        .image-container {
          width: 100%;
        }
      
        .image-container img {
          width: 100%;
          height: auto;
          display: block;
        }
      </style>
</head>
<body>
    <div class="image-container">
        <img src="/static/book/img/map2.jpg" alt="Map Image">
      </div>
    <div class="container">
        <div class="icon-container">
            <h1 class="mt-5">Online Books</h1>
            <img src="/static/book/img/book.gif" style="width: 70px;height: 70px;">
        </div>
        {% if role == 'pengguna' %}
        <div class="icon-container">
            <img src="/static/book/img/warrior.gif" style="width: 45px;height: 45px;">
            <h2> {{ username }}</h2>
        </div>
        <div class="icon-container">
            <img src="/static/book/img/yen.gif" style="width: 45px;height: 45px;">
            <h2> {{ point }} BC</h2>
        </div>
        {% elif role == 'admin' %}
        <div class="icon-container">
            <img src="/static/book/img/crown.gif" style="width: 45px;height: 45px;">
            <h2>Hallo admin {{ username }}</h2>
        </div>
        
        {% endif %}
        <div class="card-group">
            {% for book in books %}
                <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2 mb-4">
                    <div class="card" style="background-color: rgb(236, 235, 141);">
                        <a href="{% url 'books:book_detail' book.pk %}" style="text-decoration: none; color: inherit;">
                            <img class="card-img-top" src="{{ book.image_url }}" alt="{{ book.title }}">
                            <div class="card-body">
                                <h6 class="card-title" style="text-align: center;">{{ forloop.counter }}</h6>
                                <h5 class="card-title">{{ book.title }}</h5>
                                <p class="card-text">Book Id: {{ book.pk }}</p>
                                <p class="card-text">Author: {{ book.author }}</p>
                                <p class="card-text">Published Date: {{ book.category}}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
{% endblock content %}

books/templates/book_detail.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>{{ book.title }}</title>
</head>

<body>
    <div>
        <div style="text-align: center;">
            <img src="{{ book.image_url }}" alt="{{ book.title }}">
            {% if user.is_authenticated %}
                <form action="{% url 'books:add_book_to_inventory' book.pk%}" method="post">
                    {% csrf_token %}
                    <label for="folder">Choose Wishlist Folder:</label>
                    <select id="folder" name="folder" style="width: 200px;">
                        <h1>{{ user_inventories }}</h1>
                        <option value="" disabled selected>Select an option</option>
                        {% for folder in user_inventories %}
                            <option value="{{ folder.pk }}">{{ folder.name }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" name="book_id">Add to Inventory</button>
                </form>
            {% else %}
            {% endif %}
            <div>
                <h2>{{ book.title }}</h2>
                <p>Book Id: {{ book.pk }}</p>
                <p>Author: {{ book.author }}</p>
                <p>Publisher: {{ book.publisher }}</p>
                <p>Published Date: {{ book.publication_date }}</p>
                <p>Pages: {{ book.page_count }}</p>
                <p>Genre: {{ book.category }}</p>
                <p>{{ book.description }}</p>
                {% if "buyed" in finish %}
                    <p>You have bought this book yet.</p>
                {% else %}
                    <p>You haven't bought this book yet.</p>
                {% endif %}
                {% if "reviewed" in finish %}
                    <p>You have reviewed this book yet.</p>
                {% else %}
                    <p>You haven't reviewed this book yet.</p>
                {% endif %}
                {% if "readed" in finish %}
                    <p>You have read this book yet.</p>
                {% else %}
                    <p>You haven't read this book yet.</p>
                {% endif %}

                <form method="post" action="{% url 'books:book_act' book.pk %}">
                    <label for="status">Status:</label>
                    <select id="status" name="status">
                        {% if "buyed" not in finish %}
                            <option value="bought">Bought</option>
                        {% endif %}
                        {% if "reviewed" not in finish %}
                            <option value="reviewed">Reviewed</option>
                        {% endif %}
                        {% if "readed" not in finish %}
                            <option value="readed">Read</option>
                        {% endif %}
                    </select>
                    <input type="submit" value="Submit">
                </form>
                <a href="{% url 'round_table:add_forum' book.id %}" class="btn btn-primary" style="margin-right: 5px; margin-top: 5px;">Add Forum</a>
            </div>
        </div>
        
    </div>
</body>
{% endblock content %}

books/templates/remove_book.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>Remove Book by ID</title>
</head>
<body>
    <h1>Remove Book by ID</h1>
    <p>Enter the ID of the book you want to remove:</p>
    <form method="post">
        {% csrf_token %}
        <input type="number" name="pk" required>
        <button type="submit">Remove Book</button>
    </form>
    <a href="{% url 'books:display_all_books' %}">Cancel</a>
</body>
{% endblock content %}

books/templates/search_result.html
{% extends 'base.html' %}
{% block content %}
{% if results %}
    <ul>
        <div class="container">
            <h1 class="mt-5">Search Results</h1>
            <div class="card-group">
                {% for book in results %}
                    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2 mb-4">
                        <div class="card">
                            <a href="{% url 'books:book_detail' book.pk %}" style="text-decoration: none; color: inherit;">
                                <img class="card-img-top" src="{{ book.image_url }}" alt="{{ book.title }}">
                                <div class="card-body">
                                    <h6 class="card-title" style="text-align: center;">{{ forloop.counter }}</h6>
                                    <h5 class="card-title">{{ book.title }}</h5>
                                    <p class="card-text">Book Id: {{ book.pk }}</p>
                                    <p class="card-text">Author: {{ book.author }}</p>
                                    <p class="card-text">Published Date: {{ book.category}}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </ul>
{% else %}
    <p>No results found.</p>
{% endif %}
{% endblock content %}