Inventory/urls.py
from django.urls import path, include
from Inventory import views

app_name = 'Inventory'

urlpatterns = [
    path('', include('users.urls')),
    path('inventory', views.user_inventory, name='user_inventory'),
    path('get-inventory-all/', views.get_inventory_json, name='get_inventory_json'),
    path('create-folder/', views.create_folder, name='create_folder'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    # path('inventory/json-inventory/', views.view_json_inventory, name='view_json_inventory'),
    path('get-user-inventory/', views.view_json_inventory, name='view_json_inventory'),
    path('get-inventory-books/', views.view_json_inventory_book, name='view_json_inventory_books'),
    # path('inventory/json-inventory-books/<int:id>/', views.view_json_inventory_book_id, name='view_json_inventory_books_id'),
    path('get-inventory-books/<int:id>/', views.view_json_inventory_book_id, name='view_json_inventory_books_id'),
    path('create-inventory-flutter/', views.create_inventory_flutter, name='create_inventory_flutter'),
    path('delete-inventory-flutter/<int:book_id>/', views.delete_inventory_flutter, name='delete_inventory_flutter'),

]

ReadQuest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('leaderboard.urls')),
    path('', include('Inventory.urls')),
    path('', include('make_journey_jurnal.urls')),
    path('forum/', include('round_table.urls')),
    path('', include('quest.urls')),
]

books/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Your existing URL patterns
    path('search/', views.search_books, name='search_books'),
    path('add-books/', views.add_books, name='add_books'),
    path('remove-book/', views.remove_book, name='remove_book'),
    path('', views.display_all_books, name='display_all_books'),
    path('books-dataset/', views.books_dataset, name='books_dataset'),
    path('book-detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('add-book-to-inventory/<int:book_id>/', views.add_book_to_inventory, name='add_book_to_inventory'),
    path('book-act/<int:pk>/', views.book_act, name='book_act'),
    path('json-all/', views.view_json, name='json_all'),
    path('json-book/<int:pk>/', views.book_detail_json, name='book_detail_json'),
    path('add-book-to-inventory-flutter/<int:book_id>/', views.add_book_to_inventory_flutter, name='add_book_to_inventory_flutter'),
    path('json-book/<int:id>', views.view_json_book_id, name='json_book_id'),
]

Inventory/models.py
# from django.db import models
# from users.models import User
# from books.models import Book

# class Inventory(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='inventories')
#     name = models.CharField(max_length=100, default="Inventory")

# class InventoryBook(models.Model):
#     inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, related_name='books')
#     book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='inventories')

from django.db import models
from users.models import User
from books.models import Book

class Inventory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Inventory")

class InventoryBook(models.Model):
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

Inventory/forms.py
from django.forms import ModelForm
from Inventory.models import Inventory

class ProductForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ["name"]

Inventory/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect

from books.models import Book
from .models import Inventory, InventoryBook
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.views.decorators.http import require_POST
from quest.views import roler
from django.views.decorators.csrf import csrf_protect


def roler(request):
    user = request.user
    role = 'none'
    if user.role == "PENGGUNA":
        role = 'pengguna'
    elif user.role == "ADMIN":
        role = 'admin'
    return role

def user_inventory(request):
    user=request.user
    user_inventories = None
    role = None

    if user.is_authenticated:
        user_inventories = Inventory.objects.filter(user=user)
        role = roler(request)
    return render(request, 'inventory.html', {'user_inventories': user_inventories, 'role' : role})

def get_inventory_json(request):
    inventory_item = Inventory.objects.all()
    return HttpResponse(serializers.serialize('json', inventory_item))

@login_required
@csrf_protect
def create_folder(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get("name")
        new_product = Inventory.objects.create(user=user, name=name)

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@require_POST
@csrf_protect
def delete_book(request, book_id):
    book = InventoryBook.objects.get(id=book_id)

    if book.inventory.user == request.user:
        book.delete()

    return HttpResponseRedirect(reverse('Inventory:user_inventory'))

def view_json_inventory(request):
    user=request.user
    data = None
    data = Inventory.objects.filter(request.user.pk)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def view_json_inventory_book(request):
    user = request.user
    user_inventories = Inventory.objects.filter(user=user)
    data = InventoryBook.objects.filter(inventory__in=user_inventories)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def view_json_inventory_book_id(request, id):
    user = request.user
    try:
        inventory = Inventory.objects.get(user=user, id=id)
        data = InventoryBook.objects.filter(inventory=inventory)
        return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    except Inventory.DoesNotExist:
        return HttpResponseNotFound("Inventory not found")

@csrf_exempt
def create_inventory_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        inventory_data_str = json.dumps(data.get('Inventory.inventory', []))
        if inventory_data_str:
            inventory_data = json.loads(inventory_data_str)
            if inventory_data:
                inventory_entry = inventory_data[0]
                name = inventory_entry.get("fields").get("name")
                if name is not None:
                    existing_inventory = Inventory.objects.filter(user=request.user, name=name).first()
                    if existing_inventory:
                        return JsonResponse({"status": "exist"}, status=200)
                    
                    new_inventory = Inventory.objects.create(
                        user=request.user,
                        name=name,
                    )

                    new_inventory.save()

                    return JsonResponse({"status": "success"}, status=200)
    
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def delete_inventory_flutter(request, book_id):
    if request.method == 'POST':
        data = json.loads(request.body)
        inventory_data_str = json.dumps(data.get('Inventory.inventorybook', []))
        if inventory_data_str:
            inventory_data = json.loads(inventory_data_str)
            if inventory_data:
                inventory_entry = inventory_data[0]
                this_inventory = inventory_entry.get("fields")
                inventory_id = this_inventory.get('inventory')
                inventory = get_object_or_404(Inventory, pk=inventory_id)
                if InventoryBook.objects.filter(inventory=inventory, book=book_id).exists():
                    inventory_book = InventoryBook.objects.get(inventory=inventory, book=book_id)
                    inventory_book.delete()
                    return JsonResponse({"status": "success"}, status=200)
                else:
                    return JsonResponse({"status": "exist"}, status=200)

    else:
        return JsonResponse({"status": "error"}, status=401)

Inventory/templates/inventory.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="/static/inventory/styles/inventory.css">
    {% if user.is_authenticated %}
       <div class="full-container g-0 container-fluid" style="margin-bottom: 20px;">
            <div class="hero">
                <div class="hero-content">
                    <h1 class="hero-text">Create Your Library Here!</h1>
                    <button type="button" class="addlib-btn" data-bs-toggle="modal" data-bs-target="#addInventoryModal">Add Library</button>
                </div>
            </div>    
            {% for inventory in user_inventories %}
                <div class="inventory-container">
                    <h2 style="padding-left: 47px; padding-top: 20px; padding-bottom: 10px; margin-top: 5px; color: white;">{{ inventory.name }}</h2>
                    <div class="row inventory-books">
                        {% for book in inventory.inventorybook_set.all %}
                            <div class="col-md-3">
                                <div class="book-card" style="margin-top: 10px;">
                                    <div class="card" style="border-radius: 16px; padding: 10px;">
                                        <div class="card-body d-flex flex-column align-items-center justify-content-center" style="padding: 7px; margin-top: 5px;">
                                            <img src="{{ book.book.image_url }}" alt="{{ book.book.title }}" style="margin-bottom: 10px;">
                                            <h6 class="card-title" style="text-align: center; margin-bottom: 5px;">{{ book.book.title }}</h6>
                                            <h7 class="author-text" style="margin-bottom: 10px; text-align: center;">
                                                <span class="material-symbols-outlined" style="vertical-align: middle; margin-right: 5px;">draw</span>
                                                <span style="opacity: 80;">{{ book.book.author }}</span>
                                            </h7>                                                                                                                                                                           
                                            <form method="post" action="{% url 'Inventory:delete_book' book.id %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="inventory_id" value="{{ inventory.id }}">
                                                <button class="btn-delete" type="submit" style="width: 200px;border: 2px solid #c8553d; border-radius: 30px; background-color: #c8553d; color: white;">Delete From Inventory</button>
                                            </form>
                                        </div>                                    
                                    </div>
                                </div>
                            </div>                                   
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}     
       </div>   
        
        <div class="modal fade g-0 container-fluid" id="addInventoryModal" tabindex="-1" aria-labelledby="addInventoryModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" style="background-color: #ffffff;">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="addInventoryModalLabel" style="color: #588B8B; font-weight: 600;">Add New Library</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="form-label" style="color: #588B8B;">Library Name:</label>
                                <input type="text" name="name" id="name" class="form-control" placeholder="Enter Library Name" required>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn" data-bs-dismiss="modal" style="color:#588B8B">Close</button>
                        <button type="button" class="btn" id="button_add" data-bs-dismiss="modal" style="color:#ffffff; background-color: #588B8B; border: 2px; border-radius: 5px;">Add Library</button>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="row" id="product_cards">            
        </div>
        
        <script>
            function addInventory() {
                fetch("{% url 'Inventory:create_folder' %}", {
                    method: "POST",
                    body: new FormData(document.querySelector('#form'))
                })
                .then(function (response) {
                    if (response.status === 200) {
                        var myModal = new bootstrap.Modal(document.getElementById("addInventoryModal"));
                        myModal.hide();
                        document.getElementById("form").reset();
                    }
                });
                return false;
            }

            document.getElementById("button_add").onclick = addInventory;
        </script>
    {% else %}
        <div class="login-message">
            <h2>Silakan login untuk melihat inventaris Anda</h2>
            <a href="/login/" class="btn btn-primary" style="width: 200px; padding: 10px; border: 1px #c8553d;border-radius: 30px; background-color: #c8553d; ">Login</a>
        </div>
        
    {% endif %}

{% endblock %}