Inventory/urls.py
from django.urls import path, include
from Inventory import views

app_name = 'Inventory'

urlpatterns = [
    path('', include('users.urls')),
    path('inventory', views.user_inventory, name='user_inventory'),
    path('get-inventory-all/', views.get_inventory_json, name='get_inventory_json'),
    path('create-folder/', views.create_folder, name='create_folder'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    # path('inventory/json-inventory/', views.view_json_inventory, name='view_json_inventory'),
    path('get-user-inventory/', views.view_json_inventory, name='view_json_inventory'),
    path('get-inventory-books/', views.view_json_inventory_book, name='view_json_inventory_books'),
    # path('inventory/json-inventory-books/<int:id>/', views.view_json_inventory_book_id, name='view_json_inventory_books_id'),
    path('get-inventory-books/<int:id>/', views.view_json_inventory_book_id, name='view_json_inventory_books_id'),
    path('create-inventory-flutter/', views.create_inventory_flutter, name='create_inventory_flutter'),
    path('delete-inventory-flutter/<int:book_id>/', views.delete_inventory_flutter, name='delete_inventory_flutter'),

]

ReadQuest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('users.urls')),
    path('', include('leaderboard.urls')),
    path('', include('Inventory.urls')),
    path('', include('make_journey_jurnal.urls')),
    path('forum/', include('round_table.urls')),
    path('', include('quest.urls')),
]

books/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Your existing URL patterns
    path('search/', views.search_books, name='search_books'),
    path('add-books/', views.add_books, name='add_books'),
    path('remove-book/', views.remove_book, name='remove_book'),
    path('', views.display_all_books, name='display_all_books'),
    path('books-dataset/', views.books_dataset, name='books_dataset'),
    path('book-detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('add-book-to-inventory/<int:book_id>/', views.add_book_to_inventory, name='add_book_to_inventory'),
    path('book-act/<int:pk>/', views.book_act, name='book_act'),
    path('json-all/', views.view_json, name='json_all'),
    path('json-book/<int:pk>/', views.book_detail_json, name='book_detail_json'),
    path('add-book-to-inventory-flutter/<int:book_id>/', views.add_book_to_inventory_flutter, name='add_book_to_inventory_flutter'),
    path('json-book/<int:id>', views.view_json_book_id, name='json_book_id'),
]

round_table/urls.py
from django.urls import path
from .views import *

app_name = 'round_table'

urlpatterns = [
    # Your existing URL patterns
    path('', show_all_forum, name='show_all_forum'),
    path('add-forum/', add_forum, name='add_forum'),
    path('add-forum/<int:book_id>', add_forum, name='add_forum'),
    path('add-reply/<int:id>/', add_reply, name='add_reply'),
    path('<int:id>/', forum_detail, name='forum_detail'),
    path('delete-forum/<int:id>/', delete_forum, name='delete_forum'),
    path('delete-reply/<int:id>/', delete_reply, name='delete_reply'),
    path('search/', search_forums, name='search_forums'),
    path('get-forum/', get_forums_json, name='get_forums_json'),
    path('delete-forum-ajax/<int:id>/', delete_forum_ajax, name='delete_forum_ajax'),
    path('<int:forum_id>/get-replies/', get_replies_json, name='get_replies_json'),
    path('<int:forum_id>/delete-reply-ajax/<int:reply_id>/', delete_reply_ajax, name='delete_reply_ajax'),
    path('create-forum/', create_forum_flutter, name='create_forum_flutter'),
    path('create-replies/', create_replies_flutter, name='create_replies_flutter'),
    path('delete-forum-flutter/<int:id>/', delete_forum_flutter, name='delete_forum_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <link rel="stylesheet" href="{% static 'book/styles/book.css' %}"/>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        {% block meta %}
        {% endblock meta %}
    </head>
    <style>
        .icon-container{
            display: flex;
            align-items: center;
        }

        body {
            background-image: url(/static/book/img/image.png);
            /* background-color: #4FB745; */
            width: 100%;
            height: auto;
            display: block;
        }

    </style>

    <body>
        {% block header %}
        {% include 'header.html' %}
        {% endblock header %}
        {% block content %}
        {% endblock content %}
        {% block footer %}
        {% include 'footer.html' %}
        {% endblock footer %}
    </body>
</html>

templates/footer.html
<!DOCTYPE html>
<html>
<head>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        footer {
            margin-top: auto; /* Pushes the footer to the bottom of the page */
        }
    </style>
</head>
<body>
    <!-- Your content goes here -->
  
    <!-- Footer -->
    <footer class="text-center text-white" style="background-color: #F28F3B;">
        <!-- Grid container -->
        <div class="container;" style="margin-top: 30px;">
            <H3>PBP F02</H3>
        </div>
        <div class="container p-4">
            Abbilhaidar Farras Zulfikar | 
            Johanes Wisanggeni | 
            Elena Zahra Kurniawan | 
            Muhammad Hafiz | 
            Rifqi Pratama Artyanto
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: #C8853D;">
            © 2023 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">ReadQuest</a>
        </div>
        <!-- Copyright -->
    </footer>
</body>
</html>

templates/header.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
  .custom-navbar {
    background-color: #52F1EBff; /* Replace with your desired color code */
  }

  /* Change the color of the search input text */
  .custom-navbar .form-control {
    color: #FF5733; /* Replace with your desired text color */
  }
  
  /* Change the background and text color of the dropdown menu */
  .custom-navbar .dropdown-menu {
    background-color: #04eaed; /* Replace with your desired background color */
  }

  .custom-navbar .dropdown-item {
    color: #00519c; /* Replace with your desired text color */
  }
</style>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  
</div>
<div style="padding-top: 55px;">
<nav class="navbar navbar-expand-lg navbar-light custom-navbar fixed-top">
  <a class="navbar-brand" href="{% url 'books:display_all_books' %}">
        ReadQuest
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Books
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/">Online Book</a>
            <a class="dropdown-item" href="/display-all-books/">User Book</a>
          </div>
        </li>
        
        {% if role == 'pengguna' %}
        <li class="nav-item table-active">
          <a class="nav-link" href="{% url 'Inventory:user_inventory' %}">Inventory</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/forum/">Forum</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/leaderboard/">LeaderBoard</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/create-book/">Make Book</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/quest/">Quest</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/logout/">Log Out</a>
        </li>
        {% elif role == 'admin' %}
        <li class="nav-item table-active">
          <a class="nav-link" href="{% url 'Inventory:user_inventory' %}">Inventory</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/forum/">Forum</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/leaderboard/">LeaderBoard</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/create-book/">Make Book</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/quest/">Quest</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/add-books/">Add Book</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/remove-book/">Remove Book</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/logout/">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item table-active">
          <a class="nav-link" href="{% url 'Inventory:user_inventory' %}">Inventory</a>
        </li>
        <li>
          <a class="nav-link table-active" href="/forum/">Forum</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/leaderboard/">LeaderBoard</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/quest/">Quest</a>
        </li>
        <li class="nav-item table-active">
          <a class="nav-link" href="/login/">Login</a>
        </li>
        {% endif %}
      </ul>

      {% if request.path|slice:":7" == '/forum/' %}
      <form class="form-inline my-2 my-lg-0" action="{% url 'round_table:search_forums' %}" method="get">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      {% else %}
      <form class="form-inline my-2 my-lg-0" action="{% url 'books:search_books' %}" method="get">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      {% endif %}
    </div>
  </nav>
</div>
  </button>